
FROM python:3.10.7


WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y libgl1-mesa-glx


COPY . .


RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000


CMD ["python", "dlib_main.py"]
